name: my_stackz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  dio: ^5.3.3
  easy_date_timeline: ^1.1.3
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.8
  provider: ^6.1.2
  flutter_secure_storage: ^7.0.0
  shared_preferences: ^2.2.2
  google_maps_flutter:
  custom_info_window: ^1.0.1
  geolocator:
  dhttpd: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
